name: Deploy to Firebase Hosting (staging)
on:
  push:
    branches:
      - deploy/staging
jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRIP_GLOBE_VIZ }}
          channelId: live
          projectId: trip-globe-viz
          target: staging
